#!/bin/bash
#
# Entrypoint for the wg-client container. Sets up a WireGuard tunnel to the
# mitmproxy container and configures iptables to enforce it. Other containers
# share this network namespace via network_mode: "service:wg-client" and
# inherit the tunnel without needing NET_ADMIN themselves.
#
# Expects:
#   - /mitmproxy-config volume mounted (shared with the mitmproxy container)
#   - NET_ADMIN capability (for creating the WireGuard interface and iptables)
#   - net.ipv4.conf.all.src_valid_mark=1 sysctl (set via docker-compose)
#

WG_JSON="/mitmproxy-config/wireguard.conf"
DNS_CONF="/mitmproxy-config/dns.conf"
DEFAULT_NAMESERVERS=("1.1.1.1" "8.8.8.8")
DNSMASQ_CONF="/etc/dnsmasq-sandcat.conf"
# Sibling containers share wg-client's network namespace via network_mode but
# get their own /etc/resolv.conf in their own mount namespace, so they don't
# inherit the resolv.conf this script writes for wg-client. We publish it here
# for sibling app-init scripts to copy into their own /etc/resolv.conf.
SHARED_RESOLV_CONF="/run/sandcat/resolv.conf"

# NetBird mesh DNS domain for split-DNS forwarding (may be overridden per deployment).
NETBIRD_DNS_DOMAIN="${NETBIRD_DNS_DOMAIN:-netbird.selfhosted}"

# Poll a command until it returns success or a timeout is hit.
#
# Args:
#   $1     - max iterations
#   $2     - sleep seconds between iterations
#   $3     - failure message printed to stderr if the command never succeeds
#   $4..$N - command (and args) to run on each iteration
wait_until() {
    local max="$1" delay="$2" msg="$3"
    shift 3
    local attempt=0
    while ! "$@"; do
        if [[ "$attempt" -ge "$max" ]]; then
            echo "$msg" >&2
            return 1
        fi
        sleep "$delay"
        attempt=$((attempt + 1))
    done
}

# Print the upstream nameservers (one per line) the local dnsmasq should
# forward "external" queries to: from $1 (dns.conf written by the addon) when
# present and non-empty, else falling back to the hardcoded defaults.
read_upstream_nameservers() {
    local dns_conf="$1"
    local lines=()
    if [[ -f "$dns_conf" && -s "$dns_conf" ]]; then
        local line
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ -n "$line" ]] && lines+=("$line")
        done < "$dns_conf"
    fi
    [[ "${#lines[@]}" -eq 0 ]] && lines=("${DEFAULT_NAMESERVERS[@]}")
    printf '%s\n' "${lines[@]}"
}

# Print the search domains found in $1 (a resolv.conf-format file), one per
# line. Used to capture the Docker compose project's default network domain
# from the original resolv.conf so we can route those queries to Docker's
# embedded DNS at 127.0.0.11.
extract_search_domains() {
    local resolv_conf="$1"
    [[ -f "$resolv_conf" ]] || return 0
    awk '/^[[:space:]]*search[[:space:]]/ { for (i=2; i<=NF; i++) print $i }' \
        "$resolv_conf"
}

# Write a dnsmasq config that splits DNS:
#  - queries under any of the given search domains (the Docker compose project
#    network) are forwarded to Docker's embedded DNS at 127.0.0.11,
#  - everything else is forwarded to the upstream from dns.conf or defaults.
#
# Args:
#   $1     - path to dns.conf (sidecar from mitmproxy)
#   $2     - path to dnsmasq config to write
#   $3..$N - search domains routed to 127.0.0.11 (may be empty)
write_dnsmasq_conf() {
    local dns_conf="$1"
    local out="$2"
    shift 2

    {
        echo "# Auto-generated by wg-client-init.sh — do not edit."
        echo "no-resolv"
        echo "no-hosts"
        echo "listen-address=127.0.0.1"
        echo "bind-interfaces"
        echo "log-facility=-"
        echo "cache-size=1000"
        # Drop dotless and RFC1918-reverse queries instead of forwarding them.
        # Sibling-container resolution relies on libc expanding bare names via
        # the search domain into FQDNs; any single-label query that still
        # reaches dnsmasq has bypassed that path and shouldn't leak upstream.
        echo "domain-needed"
        echo "bogus-priv"
        local d
        for d in "$@"; do
            printf 'server=/%s/127.0.0.11\n' "$d"
        done
        local ns
        while IFS= read -r ns; do
            printf 'server=%s\n' "$ns"
        done < <(read_upstream_nameservers "$dns_conf")
    } > "$out"
}

# Write a resolv.conf that routes all queries through the local dnsmasq.
# Search domains are preserved so that bare hostnames (e.g. another compose
# service) get expanded by the libc resolver and routed to 127.0.0.11 by
# dnsmasq's `server=/<search>/127.0.0.11` rules.
#
# `options ndots:0` from the Docker-supplied resolv.conf is intentionally NOT
# preserved — it would defeat the search-domain expansion path that lets
# dnsmasq distinguish sibling-container queries from external ones.
#
# Args:
#   $1     - path to resolv.conf to overwrite
#   $2..$N - search domains preserved from the original file (may be empty)
write_resolv_conf() {
    local resolv_conf="$1"
    shift

    {
        echo "nameserver 127.0.0.1"
        if [[ "$#" -gt 0 ]]; then echo "search $*"; fi
    } > "$resolv_conf"
}

# Extract the first NetBird nameserver IP from `netbird status --json`.
# Outputs the IP on stdout and returns 0, or outputs nothing and returns 0 if
# DNS is not configured (caller must treat empty output as "not available").
#
# The NetBird management server pushes nameserver groups to enrolled peers;
# the JSON path tried here matches the structure emitted by NetBird >= 0.28.
netbird_dns_nameserver_ip() {
    local ns_json
    ns_json=$(netbird status --json 2>/dev/null) || return 0

    local ip
    ip=$(printf '%s' "$ns_json" | jq -r '
        first(
            (.nameservers // .dns // [])[]
            | (.servers // .ips // [])[]
            | select(type == "string" and length > 0)
        ) // empty
    ' 2>/dev/null) || true

    # Validate: accept only bare IPv4 or IPv6 addresses (no newlines, no paths,
    # no dnsmasq option syntax). Rejects anything that would inject config lines.
    if [[ -n "$ip" ]]; then
        # IPv4: four dotted octets; IPv6: colon-hex (including ::1 and full forms)
        if [[ "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] \
            || [[ "$ip" =~ ^[0-9a-fA-F:]+$ && "$ip" == *:* ]]; then
            printf '%s\n' "$ip"
        else
            echo "wg-client: netbird_dns_nameserver_ip: discarding non-IP value from JSON: ${ip@Q}" >&2
        fi
    fi
    return 0
}

# Append a NetBird domain-scoped DNS forward to the dnsmasq config and
# reload dnsmasq (SIGHUP) so queries for $NETBIRD_DNS_DOMAIN resolve via
# the NetBird nameserver instead of the catch-all upstream.
#
# Safe to call when NetBird DNS is not configured: logs one line and exits
# cleanly (does not modify the config).
#
# Args:
#   $1 - path to the dnsmasq config file to update
patch_dnsmasq_for_netbird() {
    local conf="$1"

    local ns_ip
    ns_ip=$(netbird_dns_nameserver_ip)

    if [[ -z "$ns_ip" ]]; then
        echo "wg-client: NetBird DNS nameserver not available (Nameservers: 0/0); skipping forward for ${NETBIRD_DNS_DOMAIN}." >&2
        return 0
    fi

    local forward_line="server=/${NETBIRD_DNS_DOMAIN}/${ns_ip}"

    # Idempotent: only write if line is not already present.
    if ! grep -qF "$forward_line" "$conf" 2>/dev/null; then
        printf '%s\n' "$forward_line" >> "$conf"
        echo "wg-client: added dnsmasq forward: $forward_line"
    fi

    # Reload dnsmasq to pick up the new domain forward.
    local dnsmasq_pid
    dnsmasq_pid=$(pgrep -x dnsmasq 2>/dev/null | head -1 || true)
    if [[ -n "$dnsmasq_pid" ]]; then
        kill -HUP "$dnsmasq_pid"
        echo "wg-client: dnsmasq (pid $dnsmasq_pid) reloaded for NetBird DNS forward."
    fi
}

main() {
    # Production behavior is errexit; kept inside main() so sourcing the file
    # (e.g. from bats tests) doesn't enable errexit in the caller's shell.
    set -e

    # ── Wait for mitmproxy to be ready ──────────────────────────────────────────
    # The mitmproxy container generates wireguard.conf (key pairs) on startup.
    # The docker-compose healthcheck gates us, but wait just in case.
    wait_until 60 1 \
        "Timed out waiting for mitmproxy wireguard.conf" \
        test -f "$WG_JSON"

    # ── Snapshot search domains BEFORE we overwrite resolv.conf ────────────────
    # Docker populates the container's resolv.conf with the compose project's
    # default network as a search domain. We preserve it so single-label
    # sibling-container lookups still work after dnsmasq takes over.
    local search_domains=()
    mapfile -t search_domains < <(extract_search_domains /etc/resolv.conf)

    # ── Derive WireGuard keys ───────────────────────────────────────────────────
    # mitmproxy stores its WireGuard key pairs as JSON:
    #   {"server_key": "<server-private>", "client_key": "<client-private>"}
    # We need the client's private key and the server's public key (derived from
    # the server's private key).
    local client_private_key server_private_key server_public_key mitmproxy_ip
    client_private_key=$(jq -r .client_key "$WG_JSON")
    server_private_key=$(jq -r .server_key "$WG_JSON")
    server_public_key=$(echo "$server_private_key" | wg pubkey)

    # Resolve the mitmproxy endpoint IP before setting up the tunnel, since DNS
    # won't be available through the normal path after routing is configured.
    mitmproxy_ip=$(getent hosts mitmproxy | awk '{print $1}')

    # ── Create WireGuard interface ──────────────────────────────────────────────
    # We set up WireGuard manually instead of using wg-quick because wg-quick
    # calls `sysctl -w net.ipv4.conf.all.src_valid_mark=1` which fails in Docker
    # (/proc/sys is read-only). The equivalent sysctl is pre-set via the
    # docker-compose `sysctls` option.
    ip link add wg0 type wireguard

    wg set wg0 \
        private-key <(echo "$client_private_key") \
        fwmark 51820 \
        peer "$server_public_key" \
            endpoint mitmproxy:51820 \
            allowed-ips 0.0.0.0/0,::/0

    ip address add 10.0.0.1/32 dev wg0
    ip link set mtu 1420 up dev wg0

    # ── Policy routing ──────────────────────────────────────────────────────────
    # All traffic is routed through wg0 via a custom routing table (51820).
    # WireGuard marks its own encapsulated UDP packets with fwmark 51820, which
    # exempts them from the custom table — so they use the normal default route to
    # reach the mitmproxy endpoint. The suppress_prefixlength rule ensures that
    # local/link-local routes in the main table still work (e.g. Docker DNS,
    # container-to-container traffic).
    ip -4 route add 0.0.0.0/0 dev wg0 table 51820
    ip -4 rule add not fwmark 51820 table 51820
    ip -4 rule add table main suppress_prefixlength 0
    ip -6 route add ::/0 dev wg0 table 51820
    ip -6 rule add not fwmark 51820 table 51820
    ip -6 rule add table main suppress_prefixlength 0

    # ── Firewall kill switch ────────────────────────────────────────────────────
    # iptables rules that enforce the tunnel. Without these, traffic could leak
    # via eth0 if the WireGuard interface goes down, or a process could reach
    # arbitrary IPs on the Docker network subnet directly (bypassing mitmproxy).
    #
    # Installed BEFORE dnsmasq starts so there is no window in which the
    # forwarder could send a query out via eth0 instead of wg0.
    #
    # Insert rules (-I) are evaluated first (in reverse insertion order):
    #   - All traffic on the WireGuard interface (wg0) and loopback
    #   - WireGuard's own UDP encapsulation to the mitmproxy endpoint (fwmark 51820)
    #   - Established/related return traffic on eth0 (for the WG handshake)
    #
    # Append rules (-A) handle remaining eth0 traffic in order:
    #   1. DROP direct access to the mitmproxy container (prevent proxy bypass)
    #   2. DROP access to the Docker gateway (host machine)
    #   3. ACCEPT traffic to other containers on the Docker network
    #   4. DROP everything else (external IPs)
    #
    # These rules cannot be modified by containers sharing this network namespace
    # via network_mode, because those containers don't have NET_ADMIN.
    local docker_network docker_gateway
    docker_network=$(ip -4 route show dev eth0 proto kernel | awk '{print $1}')
    docker_gateway=$(ip -4 route show default dev eth0 | awk '{print $3}')

    if [[ -z "$docker_network" || -z "$docker_gateway" ]]; then
        echo "Failed to determine Docker IPv4 network/gateway for eth0; refusing to configure iptables." >&2
        exit 1
    fi

    iptables -I OUTPUT -o wg0 -j ACCEPT
    iptables -I OUTPUT -o lo -j ACCEPT
    iptables -I OUTPUT -d "$mitmproxy_ip" -p udp --dport 51820 -m mark --mark 51820 -j ACCEPT
    iptables -I OUTPUT -o eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    iptables -A OUTPUT -o eth0 -d "$mitmproxy_ip" -j DROP
    iptables -A OUTPUT -o eth0 -d "$docker_gateway" -j DROP
    iptables -A OUTPUT -o eth0 -d "$docker_network" -j ACCEPT
    iptables -A OUTPUT -o eth0 -j DROP

    ip6tables -I OUTPUT -o wg0 -j ACCEPT
    ip6tables -I OUTPUT -o lo -j ACCEPT
    ip6tables -I OUTPUT -o eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    local docker_network_v6 docker_gateway_v6
    docker_network_v6=$(ip -6 route show dev eth0 proto kernel 2>/dev/null | awk '{print $1}')
    if [[ -n "$docker_network_v6" ]]; then
        docker_gateway_v6=$(ip -6 route show default dev eth0 2>/dev/null | awk '{print $3}')
        ip6tables -A OUTPUT -o eth0 -d "$mitmproxy_ip" -j DROP
        [[ -n "$docker_gateway_v6" ]] && ip6tables -A OUTPUT -o eth0 -d "$docker_gateway_v6" -j DROP
        ip6tables -A OUTPUT -o eth0 -d "$docker_network_v6" -j ACCEPT
    fi
    ip6tables -A OUTPUT -o eth0 -j DROP

    # ── Local DNS forwarder ────────────────────────────────────────────────────
    # Run dnsmasq on 127.0.0.1 so:
    #  - sibling-container queries (matched via the compose project's search
    #    domain) go to Docker's embedded resolver at 127.0.0.11 (loopback,
    #    NAT'd to the daemon — never enters wg0),
    #  - everything else goes to the upstream from dns.conf (or defaults),
    #    which routes through wg0 → mitmproxy for inspection and policy.
    #
    # Outbound from dnsmasq stays inside the kill-switch installed above:
    #   - 127.0.0.11 traffic uses the lo interface (ACCEPT-ed),
    #   - upstream queries go via wg0 (ACCEPT-ed).
    write_dnsmasq_conf "$DNS_CONF" "$DNSMASQ_CONF" "${search_domains[@]}"
    dnsmasq --conf-file="$DNSMASQ_CONF"

    # dnsmasq daemonizes after parsing its config; verify it actually bound
    # to 127.0.0.1:53 before we point /etc/resolv.conf at it. Without this
    # check, a post-fork crash would silently black-hole every DNS query.
    wait_until 25 0.2 \
        "dnsmasq did not start listening on 127.0.0.1:53" \
        dnsmasq-ready

    write_resolv_conf /etc/resolv.conf "${search_domains[@]}"

    # Publish the same resolv.conf for sibling containers to copy from.
    # See SHARED_RESOLV_CONF declaration for why this is necessary.
    mkdir -p "$(dirname "$SHARED_RESOLV_CONF")"
    write_resolv_conf "$SHARED_RESOLV_CONF" "${search_domains[@]}"

    # Host routing/iptables for local NetBird enrollment (literal host IP in URL).
    configure_netbird_host_management_access "$docker_gateway"

    # ── NetBird overlay mesh (optional) ─────────────────────────────────────────
    # Enroll and start the NetBird daemon if NB_SETUP_KEY is set. wt0 is created
    # by the daemon in this network namespace alongside wg0. fwmark 51821 ensures
    # wt0 traffic routes through wg0 → mitmproxy (not eth0 directly).
    trust_mitmproxy_ca "/mitmproxy-config/mitmproxy-ca-cert.pem"
    start_netbird "wt0"
    set_netbird_fwmark "wt0"
    supervise_netbird_daemon "wt0" &

    # Forward NetBird mesh DNS domain via the local dnsmasq instance so that
    # FQDNs like peer-proxy.netbird.selfhosted resolve inside the agent. This
    # is a best-effort call: if the nameserver is not yet published (dashboard
    # DNS not enabled or NetBird not fully enrolled), it logs and continues.
    patch_dnsmasq_for_netbird "$DNSMASQ_CONF"

    # Signal readiness to containers waiting on the healthcheck.
    touch /tmp/wg-ready

    supervise_dnsmasq "$DNSMASQ_CONF"
}

# Trust the mitmproxy CA cert so the netbird daemon can verify TLS connections
# to the NetBird management and signal servers. Those connections transit wg0 →
# mitmproxy just like all other outbound traffic; without this step the daemon
# would reject the MITM certificate and fail to enroll.
# Args:
#   $1 - Path to the mitmproxy CA cert (from the mitmproxy-config volume)
#   $2 - System CA directory (default: /usr/local/share/ca-certificates)
trust_mitmproxy_ca() {
    local ca_cert="$1"
    local ca_dir="${2:-/usr/local/share/ca-certificates}"
    [[ -f "$ca_cert" ]] || return 0
    cp "$ca_cert" "$ca_dir/mitmproxy.crt"
    update-ca-certificates --fresh >/dev/null 2>&1
}

# Extracts the host from an http(s) management URL.
# Args:
#   $1 - URL (e.g. http://192.168.5.2:33073)
netbird_management_url_host() {
    local url=$1

    [[ "$url" =~ ^https?://([^/:]+) ]] || return 1
    printf '%s' "${BASH_REMATCH[1]}"
}

# Returns 0 when the URL host is a literal IPv4 address.
# Args:
#   $1 - Hostname or IP
netbird_management_url_host_is_literal_ipv4() {
    local host=$1
    [[ "$host" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
}

# Extracts the TCP port from an http(s) management URL. Defaults to 443/80.
# Args:
#   $1 - URL (e.g. http://192.168.5.2:33073)
netbird_management_url_port() {
    local url=$1
    if [[ "$url" =~ :([0-9]+)(/|$|\?) ]]; then
        printf '%s' "${BASH_REMATCH[1]}"
        return 0
    fi
    if [[ "$url" =~ ^https:// ]]; then
        printf '443'
    else
        printf '80'
    fi
}

# Returns 0 when the Docker host is off the bridge subnet and must be reached
# via the bridge gateway (e.g. Colima host 192.168.5.2 on sandcat 172.23.0.0/16).
# Args:
#   $1 - Resolved host IPv4
#   $2 - Docker bridge gateway IPv4
netbird_host_route_uses_gateway() {
    local host_ip=$1
    local docker_gateway=$2

    [[ -n "$host_ip" && -n "$docker_gateway" ]] || return 1
    [[ "$host_ip" != "$docker_gateway" ]]
}

# Allow enrollment against a NetBird management server on the Docker host.
# wg-client routes most traffic through wg0; management traffic to a literal
# host IP must bypass mitmproxy via eth0. Re-apply after netbird service start
# (it may add routing rules that steal host-bound traffic).
# Args:
#   $1 - Docker bridge gateway IP
configure_netbird_host_management_access() {
    local docker_gateway=$1
    local mgmt_url="${NB_MANAGEMENT_URL:-}"
    local host_ip port

    [[ -n "${NB_SETUP_KEY:-}" ]] || return 0
    [[ -n "$docker_gateway" ]] || return 0

    host_ip=$(netbird_management_url_host "$mgmt_url") || return 0
    netbird_management_url_host_is_literal_ipv4 "$host_ip" || return 0

    port=$(netbird_management_url_port "$mgmt_url")

    if netbird_host_route_uses_gateway "$host_ip" "$docker_gateway"; then
        echo "[wg-client] Allowing NetBird management traffic to ${host_ip}:${port} via eth0 (via ${docker_gateway})." >&2
    else
        echo "[wg-client] Allowing NetBird management traffic to ${host_ip}:${port} via eth0." >&2
    fi

    # Prefer main table for host management (sandcat policy routing uses 51820 → wg0).
    ip -4 rule add to "${host_ip}/32" lookup main priority 50 2>/dev/null || true
    if netbird_host_route_uses_gateway "$host_ip" "$docker_gateway"; then
        ip -4 route add "${host_ip}/32" via "${docker_gateway}" dev eth0 table main 2>/dev/null || true
        ip -4 route add "${host_ip}/32" via "${docker_gateway}" dev eth0 table 51820 2>/dev/null || true
    else
        ip -4 route add "${host_ip}/32" dev eth0 table main 2>/dev/null || true
        ip -4 route add "${host_ip}/32" dev eth0 table 51820 2>/dev/null || true
    fi

    iptables -C OUTPUT -o eth0 -d "$host_ip" -p tcp --dport "$port" -j ACCEPT 2>/dev/null \
        || iptables -I OUTPUT 1 -o eth0 -d "$host_ip" -p tcp --dport "$port" -j ACCEPT
    iptables -C OUTPUT -o eth0 -d "$host_ip" -p udp --dport 3478 -j ACCEPT 2>/dev/null \
        || iptables -I OUTPUT 1 -o eth0 -d "$host_ip" -p udp --dport 3478 -j ACCEPT
}

# Verifies HTTP reachability to a self-hosted management server on the Docker host.
netbird_verify_host_management_reachable() {
    local mgmt_url="${NB_MANAGEMENT_URL:-}"
    local host_ip port check_url

    host_ip=$(netbird_management_url_host "$mgmt_url") || return 0
    netbird_management_url_host_is_literal_ipv4 "$host_ip" || return 0

    port=$(netbird_management_url_port "$mgmt_url")
    command -v curl >/dev/null 2>&1 || return 0

    check_url="${mgmt_url%/}/api/instance"
    wait_until 15 1 \
        "[wg-client] Cannot reach NetBird management at ${mgmt_url} from wg-client; is netbird-server running on the host (port ${port})?" \
        curl -sf --max-time 5 "$check_url" >/dev/null
}

# Writes /var/lib/netbird/default.json so the daemon keeps the enrollment URL
# instead of switching to localhost after the server registers the peer.
netbird_prepare_local_management_profile() {
    local mgmt_url="${NB_MANAGEMENT_URL:-}"
    local host profile_file="/var/lib/netbird/default.json"

    [[ -n "${NB_SETUP_KEY:-}" ]] || return 0
    host=$(netbird_management_url_host "$mgmt_url") || return 0
    netbird_management_url_host_is_literal_ipv4 "$host" || return 0

    mkdir -p "$(dirname "$profile_file")"
    if [[ -f "$profile_file" ]] && command -v jq >/dev/null 2>&1; then
        local tmp
        tmp=$(mktemp)
        jq --arg url "$mgmt_url" '.ManagementURL = $url | .AdminURL = $url' "$profile_file" >"$tmp"
        mv "$tmp" "$profile_file"
        return 0
    fi

    cat >"$profile_file" <<EOF
{
  "ManagementURL": "$mgmt_url",
  "AdminURL": "$mgmt_url",
  "WgIface": "wt0",
  "IFaceBlackList": ["docker", "br-", "veth", "wg0"],
  "BlockInbound": false,
  "BlockLANAccess": false,
  "RosenpassEnabled": false,
  "PrivateKey": ""
}
EOF
}

# Exports NetBird daemon env vars for local host-IP enrollment.
netbird_export_service_env() {
    local mgmt_url="${NB_MANAGEMENT_URL:-https://api.netbird.io}"
    export NB_MANAGEMENT_URL="$mgmt_url"
    if netbird_management_url_host_is_literal_ipv4 "$(netbird_management_url_host "$mgmt_url" 2>/dev/null)"; then
        export NB_USE_LEGACY_ROUTING=true
    fi
}

netbird_daemon_ready() {
    netbird status >/dev/null 2>&1
}

# Starts the NetBird background service (required for client 0.28+).
ensure_netbird_service() {
    [[ -n "${NB_SETUP_KEY:-}" ]] || return 0
    netbird_prepare_local_management_profile
    netbird_export_service_env
    if netbird_daemon_ready; then
        return 0
    fi

    echo "[wg-client] Starting NetBird service daemon." >&2
    netbird service run --log-file console &

    wait_until 30 1 \
        "[wg-client] Timed out waiting for NetBird service daemon" \
        netbird_daemon_ready
}

# Enroll this container as a NetBird peer and start the daemon in the background.
# Does nothing if NB_SETUP_KEY is unset (NetBird disabled for this environment).
# After the daemon starts it waits until the overlay interface appears.
# Args:
#   $1 - WireGuard interface name for the NetBird overlay (default: wt0)
start_netbird() {
    local iface="${1:-wt0}"
    local docker_gateway
    [[ -n "${NB_SETUP_KEY:-}" ]] || return 0

    docker_gateway=$(ip -4 route show default dev eth0 2>/dev/null | awk '{print $3}')

    ensure_netbird_service
    configure_netbird_host_management_access "$docker_gateway"
    netbird_verify_host_management_reachable
    netbird_prepare_local_management_profile
    if [[ -f /var/lib/netbird/default.json ]] \
        && grep -qE 'localhost|127\.0\.0\.1|\[::1\]' /var/lib/netbird/default.json 2>/dev/null; then
        netbird down 2>/dev/null || true
    fi
    netbird_export_service_env

    echo "[wg-client] Enrolling NetBird peer on ${iface}." >&2
    netbird up \
        --setup-key "${NB_SETUP_KEY}" \
        --management-url "${NB_MANAGEMENT_URL:-https://api.netbird.io}" \
        --interface-name "${iface}"

    wait_until 30 1 \
        "[wg-client] Timed out waiting for NetBird to bring up ${iface}" \
        ip link show "${iface}" >/dev/null 2>&1
}

# Override the WireGuard fwmark on the NetBird interface so its encapsulation
# packets (fwmark 51821) are NOT exempt from the wg0 policy routing rule
# (`not fwmark 51820 → table 51820 → wg0`). This ensures NetBird peer traffic
# transits wg0 → mitmproxy, preserving the inspection guarantee.
# Must be called after start_netbird has brought the interface up.
# Args:
#   $1 - NetBird WireGuard interface name (default: wt0)
set_netbird_fwmark() {
    local iface="${1:-wt0}"
    ip link show "${iface}" >/dev/null 2>&1 || return 0
    wg set "${iface}" fwmark 51821
}

# Supervise the NetBird daemon: poll every 10 s and restart if unresponsive.
# Returns immediately (no-op) if NB_SETUP_KEY is unset.
# Args:
#   $1 - NetBird WireGuard interface name (default: wt0)
supervise_netbird_daemon() {
    local iface="${1:-wt0}"
    [[ -n "${NB_SETUP_KEY:-}" ]] || return 0

    while true; do
        sleep 10
        if ! netbird_daemon_ready; then
            echo "[wg-client] NetBird service daemon not responding; restarting." >&2
            netbird_export_service_env
            netbird service run --log-file console &
            wait_until 15 1 \
                "[wg-client] Timed out waiting for NetBird service daemon" \
                netbird_daemon_ready || true
        fi
        if ! ip link show "${iface}" >/dev/null 2>&1; then
            echo "[wg-client] NetBird interface ${iface} down; re-enrolling." >&2
            docker_gateway=$(ip -4 route show default dev eth0 2>/dev/null | awk '{print $3}')
            configure_netbird_host_management_access "$docker_gateway"
            netbird_prepare_local_management_profile
            netbird_export_service_env
            netbird up \
                --setup-key "${NB_SETUP_KEY}" \
                --management-url "${NB_MANAGEMENT_URL:-https://api.netbird.io}" \
                --interface-name "${iface}" || true
            set_netbird_fwmark "${iface}" || true
        fi
        # Retry the NetBird DNS forward on every iteration. patch_dnsmasq_for_netbird
        # is idempotent (skips if the line is already present), so this is safe.
        # Nameservers are pushed from the management server after enrollment;
        # they may not be available at container start time.
        patch_dnsmasq_for_netbird "${DNSMASQ_CONF}" 2>/dev/null || true
    done
}

# Keep dnsmasq alive in-place. Sibling containers share this container's
# network namespace via `network_mode: service:wg-client`; that binding is
# resolved at sibling-create time, so a wg-client container restart would
# leave the agent attached to a now-destroyed namespace. Supervising dnsmasq
# locally — instead of letting the container exit and rely on Docker's
# restart policy — keeps the namespace intact across dnsmasq crashes.
supervise_dnsmasq() {
    local conf="$1"
    while true; do
        sleep 5
        if ! dnsmasq-ready; then
            echo "[wg-client] dnsmasq not listening; restarting" >&2
            dnsmasq --conf-file="$conf" || true
        fi
    done
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
    main "$@"
fi
