FROM mcr.microsoft.com/devcontainers/rust:2-1-trixie

COPY scripts/install-ca-cert.sh /usr/local/bin/install-ca-cert.sh
RUN chmod +x /usr/local/bin/install-ca-cert.sh

ENTRYPOINT ["/usr/local/bin/install-ca-cert.sh"]
