#!/usr/bin/env bash
# Appends a sandcat-managed section to the project's .gitignore so users
# don't accidentally commit `.devcontainer/` (regenerated by `sandcat init`)
# or `.sandcat/settings.local.json` (per-machine secrets). Team-shared
# entries like `.devcontainer/devbox.tools.json` are re-included via a
# git negation pattern so they still travel with the repo.
#
# The block is bracketed by "# Sandcat" and "# /Sandcat" comment lines
# so we can also remove it symmetrically when the user opts out via
# `--features no-gitignore` on a subsequent `sandcat init`.

# Sentinel comments — start and end of the sandcat-managed block. Both
# must be plain lines (whole-line-match with grep -qxF) so they survive
# accidental substring matching in user rules.
SCT_GITIGNORE_MARKER="# Sandcat"
SCT_GITIGNORE_END_MARKER="# /Sandcat"

# Appends the sandcat block to project_path/.gitignore.
# Skips silently when:
#   * project_path/.git does not exist (not a git working tree)
#   * .gitignore already contains the sandcat marker (idempotent re-run)
# Creates .gitignore if missing.
#
# Args:
#   $1 - Project root path
update_gitignore() {
	local project_path=$1

	# Non-git project — nothing to gitignore into.
	[[ -e "$project_path/.git" ]] || return 0

	local gitignore="$project_path/.gitignore"
	if [[ -f "$gitignore" ]] && grep -qxF "$SCT_GITIGNORE_MARKER" "$gitignore"; then
		# Already applied on a previous init; keep the user's edits.
		return 0
	fi

	# Ensure the file ends with a newline before appending so we don't
	# glue our block onto the user's last line. Bash command substitution
	# strips trailing newlines, so `$(tail -c1)` on a file whose last byte
	# IS a newline yields "" — we detect that with -n, meaning the last
	# byte was retained and therefore is NOT a newline.
	if [[ -s "$gitignore" ]] && [[ -n "$(tail -c1 "$gitignore" 2>/dev/null)" ]]; then
		printf '\n' >> "$gitignore"
	fi

	# Blank line before our block for readability when appending to an
	# existing .gitignore.
	[[ -s "$gitignore" ]] && printf '\n' >> "$gitignore"

	cat >> "$gitignore" <<EOF
$SCT_GITIGNORE_MARKER
# Regenerated by \`sandcat init\`. Everything else under .devcontainer/
# is regenerated on next init or contains per-machine state; only
# devbox.tools.json is your project-shared tool list and stays in git.
# Sandcat manages this whole block; re-running init with
# \`--features no-gitignore\` (or SANDCAT_GITIGNORE=false) removes it.
.devcontainer/*
!.devcontainer/devbox.tools.json
.sandcat/settings.local.json
$SCT_GITIGNORE_END_MARKER
EOF
}

# Removes the sandcat-managed block from .gitignore, including both
# marker lines and any preceding blank-line separator that update_gitignore
# introduced. Silent no-op when:
#   * project_path/.git does not exist (not a git working tree)
#   * .gitignore is missing or does not contain the start marker
#
# Anything the user hand-added BETWEEN the two markers is removed too —
# customising inside the block isn't supported. Rules outside the
# markers are preserved verbatim.
#
# Args:
#   $1 - Project root path
remove_gitignore_block() {
	local project_path=$1

	[[ -e "$project_path/.git" ]] || return 0

	local gitignore="$project_path/.gitignore"
	[[ -f "$gitignore" ]] || return 0
	grep -qxF "$SCT_GITIGNORE_MARKER" "$gitignore" || return 0

	local tmp
	tmp=$(mktemp)
	# awk: drop lines between the two markers (inclusive), and if the
	# line immediately before the start marker was blank, drop that too
	# so we don't leave a stranded separator behind.
	awk -v start="$SCT_GITIGNORE_MARKER" -v end="$SCT_GITIGNORE_END_MARKER" '
		# Buffer everything so we can retroactively drop the blank line
		# before the start marker.
		{ line[NR] = $0 }
		END {
			for (i = 1; i <= NR; i++) {
				if (line[i] == start) {
					# Drop preceding blank line, if any, from our output.
					if (out_count > 0 && out[out_count] == "") out_count--
					# Skip until we see the end marker.
					while (i <= NR && line[i] != end) i++
					continue  # for-loop step advances past `end`
				}
				out[++out_count] = line[i]
			}
			for (i = 1; i <= out_count; i++) print out[i]
		}
	' "$gitignore" > "$tmp"

	# If the tmp is now empty (block was the only content), remove
	# the file entirely — mirrors the pre-init state.
	if [[ -s "$tmp" ]]; then
		mv "$tmp" "$gitignore"
	else
		rm "$tmp" "$gitignore"
	fi
}
